const data = [
  {
    id: 1,
    fullName: "Jerrold Yeend",
    avatar: "https://robohash.org/porrocupiditateet.png?size=50x50&set=set1",
    university: "Indian Institute of Technology, Kanpur",
    department: "Research and Development",
  },
  {
    id: 2,
    fullName: "Florian Errey",
    avatar: "https://robohash.org/autemautquae.png?size=50x50&set=set1",
    university: "Bluefield College",
    department: "Legal",
  },
  {
    id: 3,
    fullName: "Darby Emanulsson",
    avatar:
      "https://robohash.org/doloribusexercitationemsequi.png?size=50x50&set=set1",
    university: "École des Hautes Études Commerciales",
    department: "Business Development",
  },
  {
    id: 4,
    fullName: "Germaine Waldocke",
    avatar: "https://robohash.org/eligendisedrem.png?size=50x50&set=set1",
    university: "Osaka University of Health and Sport Sciences",
    department: "Research and Development",
  },
  {
    id: 5,
    fullName: "Sebastian Siddaley",
    avatar: "https://robohash.org/quinumquammollitia.png?size=50x50&set=set1",
    university: "Strathmore University",
    department: "Product Management",
  },
  {
    id: 6,
    fullName: "Quintin Baldacco",
    avatar:
      "https://robohash.org/ettemporibusconsectetur.png?size=50x50&set=set1",
    university: "Asia E University",
    department: "Engineering",
  },
  {
    id: 7,
    fullName: "Darda Livens",
    avatar: "https://robohash.org/perferendisverout.png?size=50x50&set=set1",
    university: "Indian Institute of Technology, Bombay",
    department: "Services",
  },
  {
    id: 8,
    fullName: "Liz Cannon",
    avatar: "https://robohash.org/doloresetnulla.png?size=50x50&set=set1",
    university: "Sichuan International Studies University",
    department: "Support",
  },
  {
    id: 9,
    fullName: "Oby Gewer",
    avatar: "https://robohash.org/exsimiliqueut.png?size=50x50&set=set1",
    university: "Universidad San Francisco de Quito",
    department: "Support",
  },
  {
    id: 10,
    fullName: "Elysee Petrovykh",
    avatar: "https://robohash.org/corruptieaqueex.png?size=50x50&set=set1",
    university: "Université de Toliary",
    department: "Engineering",
  },
  {
    id: 11,
    fullName: "Silvain Hugnot",
    avatar: "https://robohash.org/utautunde.png?size=50x50&set=set1",
    university: "Omsk State Agrarian University",
    department: "Research and Development",
  },
  {
    id: 12,
    fullName: "Avivah Duro",
    avatar: "https://robohash.org/idveniamincidunt.png?size=50x50&set=set1",
    university: "Universidad Franco-Mexicana",
    department: "Accounting",
  },
  {
    id: 13,
    fullName: "Julienne Strother",
    avatar: "https://robohash.org/autestdolore.png?size=50x50&set=set1",
    university: "Fahad Bin Sultan University",
    department: "Legal",
  },
  {
    id: 14,
    fullName: "Riane Furse",
    avatar: "https://robohash.org/nondelenitilibero.png?size=50x50&set=set1",
    university: "Technikum Wien",
    department: "Business Development",
  },
  {
    id: 15,
    fullName: "Noelle Bertholin",
    avatar: "https://robohash.org/etdoloriste.png?size=50x50&set=set1",
    university: "Thaksin University",
    department: "Sales",
  },
  {
    id: 16,
    fullName: "Nelia Emlyn",
    avatar: "https://robohash.org/quicorporisdeleniti.png?size=50x50&set=set1",
    university: "Guru Ghasidas University",
    department: "Business Development",
  },
  {
    id: 17,
    fullName: "Dorene Giovannacc@i",
    avatar: "https://robohash.org/enimetnemo.png?size=50x50&set=set1",
    university: "Idaho State University",
    department: "Accounting",
  },
  {
    id: 18,
    fullName: "Wendell Sollime",
    avatar: "https://robohash.org/repellatmolestiaeut.png?size=50x50&set=set1",
    university: "Yorker International University, Milano",
    department: "Accounting",
  },
  {
    id: 19,
    fullName: "Tommie Ingamells",
    avatar: "https://robohash.org/remrepudiandaeatque.png?size=50x50&set=set1",
    university: "Wakayama University",
    department: "Business Development",
  },
  {
    id: 20,
    fullName: "Land Shimuk",
    avatar:
      "https://robohash.org/undeconsequunturdolorum.png?size=50x50&set=set1",
    university: "Theologische Hochschule Friedensau",
    department: "Human Resources",
  },
  {
    id: 21,
    fullName: "Vergil Borleace",
    avatar:
      "https://robohash.org/necessitatibuspraesentiummaxime.png?size=50x50&set=set1",
    university: "Sapporo International University",
    department: "Human Resources",
  },
  {
    id: 22,
    fullName: "Annmarie Letch",
    avatar:
      "https://robohash.org/magnampraesentiumnisi.png?size=50x50&set=set1",
    university: "Universitas Islam Sumatera Utara",
    department: "Business Development",
  },
  {
    id: 23,
    fullName: "Colet Ibbetson",
    avatar:
      "https://robohash.org/necessitatibuseumveniam.png?size=50x50&set=set1",
    university: "University of Mkar",
    department: "Accounting",
  },
  {
    id: 24,
    fullName: "Lorenza Breawood",
    avatar: "https://robohash.org/optioquiavoluptatem.png?size=50x50&set=set1",
    university: "Westminster College Fulton",
    department: "Support",
  },
  {
    id: 25,
    fullName: "Carmelle Klais",
    avatar: "https://robohash.org/sitnisiofficiis.png?size=50x50&set=set1",
    university: "Capital University Law School",
    department: "Business Development",
  },
  {
    id: 26,
    fullName: "Athene Bushnell",
    avatar: "https://robohash.org/eligendiiustout.png?size=50x50&set=set1",
    university: "St. Petersburg State Cinema and TV University",
    department: "Business Development",
  },
  {
    id: 27,
    fullName: "Maisey Shepherdson",
    avatar: "https://robohash.org/eumestut.png?size=50x50&set=set1",
    university: "Kwara State University ",
    department: "Product Management",
  },
  {
    id: 28,
    fullName: "Chrysa Sinderland",
    avatar:
      "https://robohash.org/perspiciatisnamaliquam.png?size=50x50&set=set1",
    university: "Mersin University",
    department: "Services",
  },
  {
    id: 29,
    fullName: "Gerladina Hugonet",
    avatar: "https://robohash.org/abvoluptaslaudantium.png?size=50x50&set=set1",
    university: "Bethel College Mishawaka",
    department: "Business Development",
  },
  {
    id: 30,
    fullName: "Hillary Lawtie",
    avatar: "https://robohash.org/accusamusautsunt.png?size=50x50&set=set1",
    university: "Bowen University",
    department: "Training",
  },
  {
    id: 31,
    fullName: "Morgan Swynley",
    avatar:
      "https://robohash.org/maximeaccusantiumtotam.png?size=50x50&set=set1",
    university: "Kanagawa University",
    department: "Human Resources",
  },
  {
    id: 32,
    fullName: "Rudolfo Rendle",
    avatar: "https://robohash.org/inremvoluptatem.png?size=50x50&set=set1",
    university: "Universidad Abierta y a Distancia de Panama",
    department: "Human Resources",
  },
  {
    id: 33,
    fullName: "Yale Hitzke",
    avatar: "https://robohash.org/temporafugitfacere.png?size=50x50&set=set1",
    university: "Boise State University",
    department: "Accounting",
  },
  {
    id: 34,
    fullName: "Rudie Roath",
    avatar: "https://robohash.org/officiaeteum.png?size=50x50&set=set1",
    university: "Universidad Nacional de Entre Ríos",
    department: "Research and Development",
  },
  {
    id: 35,
    fullName: "Alvis Cronk",
    avatar:
      "https://robohash.org/optiodoloribusdeserunt.png?size=50x50&set=set1",
    university: 'Universidad Nacional Experimental "Rafael Maria Baralt"',
    department: "Engineering",
  },
  {
    id: 36,
    fullName: "Yorke Symonds",
    avatar:
      "https://robohash.org/errordeseruntvoluptatem.png?size=50x50&set=set1",
    university: "Universidad Pedagógica y Tecnológica de Colombia",
    department: "Legal",
  },
  {
    id: 37,
    fullName: "Clifford Woofendell",
    avatar:
      "https://robohash.org/natusvoluptatemaliquid.png?size=50x50&set=set1",
    university: "Danish Business Academy",
    department: "Product Management",
  },
  {
    id: 38,
    fullName: "Donna Pell",
    avatar: "https://robohash.org/rerumquodet.png?size=50x50&set=set1",
    university: "Assumption University of Thailand",
    department: "Business Development",
  },
  {
    id: 39,
    fullName: "Rosa Judron",
    avatar: "https://robohash.org/quodolorumsed.png?size=50x50&set=set1",
    university: "Pädagogische Hochschule Erfurt/Mühlhausen",
    department: "Business Development",
  },
  {
    id: 40,
    fullName: "Pebrook Youel",
    avatar: "https://robohash.org/etautamet.png?size=50x50&set=set1",
    university: "University of Oregon",
    department: "Engineering",
  },
  {
    id: 41,
    fullName: "Rosy Winders",
    avatar: "https://robohash.org/voluptatemautfugiat.png?size=50x50&set=set1",
    university: "Universidad de San Buenaventura",
    department: "Legal",
  },
  {
    id: 42,
    fullName: "Alfi Backson",
    avatar: "https://robohash.org/corruptiquasieaque.png?size=50x50&set=set1",
    university: "Baghyatoolah Medical Sciences University",
    department: "Accounting",
  },
  {
    id: 43,
    fullName: "Parsifal Barchrameev",
    avatar: "https://robohash.org/doloremquefacereeos.png?size=50x50&set=set1",
    university: "Texas Chiropractic College",
    department: "Sales",
  },
  {
    id: 44,
    fullName: "Bendick Asmus",
    avatar: "https://robohash.org/enimaliasexplicabo.png?size=50x50&set=set1",
    university: "International Banking Institute, St. Petersburg",
    department: "Research and Development",
  },
  {
    id: 45,
    fullName: "Elsinore Bertomeu",
    avatar: "https://robohash.org/etvitaesimilique.png?size=50x50&set=set1",
    university: "Örebro University",
    department: "Sales",
  },
  {
    id: 46,
    fullName: "Ganny Ramsby",
    avatar:
      "https://robohash.org/inciduntmollitiavoluptate.png?size=50x50&set=set1",
    university: "University of Marketing and Distribution Sciences",
    department: "Sales",
  },
  {
    id: 47,
    fullName: "Teddie Berney",
    avatar: "https://robohash.org/sedquasconsectetur.png?size=50x50&set=set1",
    university: "Universitas Jayabaya",
    department: "Product Management",
  },
  {
    id: 48,
    fullName: "Adelice Frowde",
    avatar: "https://robohash.org/harumfugaet.png?size=50x50&set=set1",
    university: "University of Jos",
    department: "Training",
  },
  {
    id: 49,
    fullName: "Gale Linnit",
    avatar: "https://robohash.org/nonrationerecusandae.png?size=50x50&set=set1",
    university: "Universidad ORT Uruguay",
    department: "Engineering",
  },
  {
    id: 50,
    fullName: "Halley Gounard",
    avatar: "https://robohash.org/quaenemodeleniti.png?size=50x50&set=set1",
    university: "Universidade Católica de Goiás",
    department: "Legal",
  },
  {
    id: 51,
    fullName: "Shalne Fulun",
    avatar: "https://robohash.org/numquamvelittempora.png?size=50x50&set=set1",
    university: "Morioka College",
    department: "Sales",
  },
  {
    id: 52,
    fullName: "West Wedlock",
    avatar:
      "https://robohash.org/fugitexpeditapraesentium.png?size=50x50&set=set1",
    university: "Universidad de Huánuco",
    department: "Support",
  },
  {
    id: 53,
    fullName: "Ariel Graalmans",
    avatar: "https://robohash.org/idestmagni.png?size=50x50&set=set1",
    university: "University of Plymouth",
    department: "Product Management",
  },
  {
    id: 54,
    fullName: "Fonsie Oswick",
    avatar: "https://robohash.org/faceremodicommodi.png?size=50x50&set=set1",
    university: "Zhetysu State University ",
    department: "Services",
  },
  {
    id: 55,
    fullName: "Vasily Ohlsen",
    avatar: "https://robohash.org/magnamnondolores.png?size=50x50&set=set1",
    university: "Moscow State University",
    department: "Marketing",
  },
  {
    id: 56,
    fullName: "Lee Allinson",
    avatar: "https://robohash.org/odioveniamdolor.png?size=50x50&set=set1",
    university: "Institut Catholique de Paris",
    department: "Business Development",
  },
  {
    id: 57,
    fullName: "Tynan Guitel",
    avatar: "https://robohash.org/voluptatumquiaex.png?size=50x50&set=set1",
    university: "Kent State University - Tuscarawas",
    department: "Services",
  },
  {
    id: 58,
    fullName: "Siouxie Crosser",
    avatar: "https://robohash.org/laudantiumarem.png?size=50x50&set=set1",
    university: "North West Frontier Province Agricultural University",
    department: "Legal",
  },
  {
    id: 59,
    fullName: "Kleon Mival",
    avatar:
      "https://robohash.org/estrepudiandaeexcepturi.png?size=50x50&set=set1",
    university: "Asahi University",
    department: "Engineering",
  },
  {
    id: 60,
    fullName: "Jess Cullabine",
    avatar:
      "https://robohash.org/doloremquelaudantiumut.png?size=50x50&set=set1",
    university: "Luther College",
    department: "Accounting",
  },
  {
    id: 61,
    fullName: "Arabelle Wixon",
    avatar: "https://robohash.org/odittemporaharum.png?size=50x50&set=set1",
    university: "World Maritime University",
    department: "Legal",
  },
  {
    id: 62,
    fullName: "Bob Blazhevich",
    avatar:
      "https://robohash.org/doloribusaliquamvoluptates.png?size=50x50&set=set1",
    university: "University of San Francisco",
    department: "Legal",
  },
  {
    id: 63,
    fullName: "Riannon Spary",
    avatar: "https://robohash.org/sedvelet.png?size=50x50&set=set1",
    university: "University of Kent at Canterbury",
    department: "Research and Development",
  },
  {
    id: 64,
    fullName: "Tobe McAllister",
    avatar: "https://robohash.org/quiaenimerror.png?size=50x50&set=set1",
    university: "University of St. Jerome's College",
    department: "Marketing",
  },
  {
    id: 65,
    fullName: "Allys Mabbott",
    avatar: "https://robohash.org/aliquamrecusandaeaut.png?size=50x50&set=set1",
    university: "Mother Teresa Women's University",
    department: "Legal",
  },
  {
    id: 66,
    fullName: "Noe Baudts",
    avatar: "https://robohash.org/excepturisaepeea.png?size=50x50&set=set1",
    university: "Arkansas State University, Newport",
    department: "Research and Development",
  },
  {
    id: 67,
    fullName: "Brigida MacGoun",
    avatar: "https://robohash.org/cumqueliberoculpa.png?size=50x50&set=set1",
    university: "Universitas Jayabaya",
    department: "Business Development",
  },
  {
    id: 68,
    fullName: "Eb MacKibbon",
    avatar:
      "https://robohash.org/distinctioquodlaboriosam.png?size=50x50&set=set1",
    university: "Southampton Solent University",
    department: "Accounting",
  },
  {
    id: 69,
    fullName: "Pepi Tizzard",
    avatar: "https://robohash.org/odioetest.png?size=50x50&set=set1",
    university: "Faculdade Italo Brasileira",
    department: "Support",
  },
  {
    id: 70,
    fullName: "Radcliffe Bethel",
    avatar: "https://robohash.org/ipsamutalias.png?size=50x50&set=set1",
    university: "Nizhny Novgorod State Academy of Medicine",
    department: "Research and Development",
  },
  {
    id: 71,
    fullName: "Valle McTrustam",
    avatar: "https://robohash.org/hictemporeexcepturi.png?size=50x50&set=set1",
    university: "Ondo State University of Science and Technology",
    department: "Business Development",
  },
  {
    id: 72,
    fullName: "Gabbie Murray",
    avatar: "https://robohash.org/consecteturnonodit.png?size=50x50&set=set1",
    university: "California School of Professional Psychology - Fresno",
    department: "Human Resources",
  },
  {
    id: 73,
    fullName: "Bettine Schukert",
    avatar: "https://robohash.org/quiavelitvoluptatem.png?size=50x50&set=set1",
    university: "Universidad Nacional Experimental de Guayana",
    department: "Sales",
  },
  {
    id: 74,
    fullName: "Zsazsa Cortez",
    avatar: "https://robohash.org/etaliquamiure.png?size=50x50&set=set1",
    university: "Instituts Supérieurs de Formation des Maîtres",
    department: "Services",
  },
  {
    id: 75,
    fullName: "Duffie Dugdale",
    avatar: "https://robohash.org/natusdolorquo.png?size=50x50&set=set1",
    university: "European Management School",
    department: "Services",
  },
  {
    id: 76,
    fullName: "Rory Ladson",
    avatar:
      "https://robohash.org/voluptatumquidemquasi.png?size=50x50&set=set1",
    university: "Manhattan Christian College",
    department: "Accounting",
  },
  {
    id: 77,
    fullName: "Michail Pearle",
    avatar:
      "https://robohash.org/quiquasexercitationem.png?size=50x50&set=set1",
    university: "CCS Haryana Agricultural University",
    department: "Training",
  },
  {
    id: 78,
    fullName: "Tadeo Dresser",
    avatar:
      "https://robohash.org/necessitatibusmodienim.png?size=50x50&set=set1",
    university: "Southern Oregon University",
    department: "Sales",
  },
  {
    id: 79,
    fullName: "Letta Hurrion",
    avatar: "https://robohash.org/dolordeseruntdolor.png?size=50x50&set=set1",
    university: "Hobe Sound Bible College",
    department: "Research and Development",
  },
  {
    id: 80,
    fullName: "Margy Leisman",
    avatar: "https://robohash.org/quiacumqueet.png?size=50x50&set=set1",
    university: "Technological University (West Yangon)",
    department: "Accounting",
  },
  {
    id: 81,
    fullName: "Birk Hughes",
    avatar: "https://robohash.org/omnisconsecteturfuga.png?size=50x50&set=set1",
    university: "Université René Descartes (Paris V)",
    department: "Support",
  },
  {
    id: 82,
    fullName: "Basile Baff",
    avatar: "https://robohash.org/veniamoptiocum.png?size=50x50&set=set1",
    university: "Belarussian State Agricultural Academy",
    department: "Accounting",
  },
  {
    id: 83,
    fullName: "Jeni Stickley",
    avatar: "https://robohash.org/totamnihilaliquid.png?size=50x50&set=set1",
    university: "Universidad la Concordia",
    department: "Research and Development",
  },
  {
    id: 84,
    fullName: "Joice Lingfoot",
    avatar: "https://robohash.org/enimavero.png?size=50x50&set=set1",
    university: "China Pharmaceutical University Nanjing",
    department: "Marketing",
  },
  {
    id: 85,
    fullName: "Jinny Povall",
    avatar: "https://robohash.org/rerumreiciendisquia.png?size=50x50&set=set1",
    university: "Agricultural University of Wroclaw",
    department: "Legal",
  },
  {
    id: 86,
    fullName: "Kev Antrobus",
    avatar: "https://robohash.org/estducimusab.png?size=50x50&set=set1",
    university: "Far Eastern State Technical University",
    department: "Research and Development",
  },
  {
    id: 87,
    fullName: "Webster Gritland",
    avatar: "https://robohash.org/inexplicaboomnis.png?size=50x50&set=set1",
    university: "Amravati University",
    department: "Business Development",
  },
  {
    id: 88,
    fullName: "Daren Faltin",
    avatar: "https://robohash.org/mollitianumquamdolor.png?size=50x50&set=set1",
    university: "Abilene Christian University",
    department: "Engineering",
  },
  {
    id: 89,
    fullName: "Fayth Dews",
    avatar: "https://robohash.org/solutaetalias.png?size=50x50&set=set1",
    university: "Universidad Nacional de San Luis",
    department: "Services",
  },
  {
    id: 90,
    fullName: "Matt De Domenicis",
    avatar: "https://robohash.org/veloccaecatieum.png?size=50x50&set=set1",
    university: "College in Sládkovičovo",
    department: "Engineering",
  },
  {
    id: 91,
    fullName: "Obadias MacCurley",
    avatar: "https://robohash.org/atetet.png?size=50x50&set=set1",
    university: "Oakton Community College",
    department: "Product Management",
  },
  {
    id: 92,
    fullName: "Lavinia Gorstidge",
    avatar: "https://robohash.org/quodoloribusneque.png?size=50x50&set=set1",
    university: "Universidade Católica de Goiás",
    department: "Engineering",
  },
  {
    id: 93,
    fullName: "Leena Gelsthorpe",
    avatar: "https://robohash.org/esseexcepturiratione.png?size=50x50&set=set1",
    university: "Universidad Politécnica de Cartagena",
    department: "Product Management",
  },
  {
    id: 94,
    fullName: "Shannah Rackley",
    avatar: "https://robohash.org/aperiammagnamdicta.png?size=50x50&set=set1",
    university: "An-Najah National University",
    department: "Sales",
  },
  {
    id: 95,
    fullName: "Emlyn Leneham",
    avatar:
      "https://robohash.org/aliasaperiammolestiae.png?size=50x50&set=set1",
    university: "St. Joseph College",
    department: "Business Development",
  },
  {
    id: 96,
    fullName: "Ignaz Freak",
    avatar: "https://robohash.org/voluptatumautemrerum.png?size=50x50&set=set1",
    university: "Karadeniz Technical University",
    department: "Marketing",
  },
  {
    id: 97,
    fullName: "Almeta Stutter",
    avatar: "https://robohash.org/autfugitofficia.png?size=50x50&set=set1",
    university: "McMurry University",
    department: "Research and Development",
  },
  {
    id: 98,
    fullName: "Sid Mallock",
    avatar:
      "https://robohash.org/voluptatemomnisnecessitatibus.png?size=50x50&set=set1",
    university: "Napier University",
    department: "Engineering",
  },
  {
    id: 99,
    fullName: "Bebe Deamer",
    avatar: "https://robohash.org/rerumetaut.png?size=50x50&set=set1",
    university: "Centro Universitario Villanueva",
    department: "Services",
  },
  {
    id: 100,
    fullName: "Noll Leahair",
    avatar: "https://robohash.org/estsaepeautem.png?size=50x50&set=set1",
    university: "Benedictine College",
    department: "Engineering",
  },
  {
    id: 101,
    fullName: "Calv Heining",
    avatar:
      "https://robohash.org/omnisaperiampraesentium.png?size=50x50&set=set1",
    university: "Kobe University of Mercantile Marine",
    department: "Product Management",
  },
  {
    id: 102,
    fullName: "Blithe Kelleway",
    avatar: "https://robohash.org/doloremetut.png?size=50x50&set=set1",
    university: "National Agricultural University",
    department: "Legal",
  },
  {
    id: 103,
    fullName: "Sophronia Killingsworth",
    avatar:
      "https://robohash.org/reiciendisautexercitationem.png?size=50x50&set=set1",
    university: "Russell Berrie Nanotechnology Institute",
    department: "Training",
  },
  {
    id: 104,
    fullName: "Cort Haglinton",
    avatar: "https://robohash.org/dignissimoseumautem.png?size=50x50&set=set1",
    university: "University of Kalamoon",
    department: "Business Development",
  },
  {
    id: 105,
    fullName: "Mandy Swane",
    avatar: "https://robohash.org/veritatisitaqueaut.png?size=50x50&set=set1",
    university: "Johann Wolfgang Goethe Universität Frankfurt am Main",
    department: "Engineering",
  },
  {
    id: 106,
    fullName: "Devin Wildbore",
    avatar: "https://robohash.org/etoditquo.png?size=50x50&set=set1",
    university: "Russian State Medical University",
    department: "Engineering",
  },
  {
    id: 107,
    fullName: "Halli Augustin",
    avatar: "https://robohash.org/quonobisdeserunt.png?size=50x50&set=set1",
    university: "University of Reggio Calabria",
    department: "Training",
  },
  {
    id: 108,
    fullName: "Raven Courvert",
    avatar: "https://robohash.org/quiatqueut.png?size=50x50&set=set1",
    university: "Merkur Internationale FH Karlsruhe",
    department: "Marketing",
  },
  {
    id: 109,
    fullName: "Romy Pound",
    avatar: "https://robohash.org/enimnamest.png?size=50x50&set=set1",
    university: "University of California, Santa Barbara",
    department: "Human Resources",
  },
  {
    id: 110,
    fullName: "Esra Maccree",
    avatar: "https://robohash.org/eosetdoloremque.png?size=50x50&set=set1",
    university: "Renmin University of China",
    department: "Research and Development",
  },
  {
    id: 111,
    fullName: "Forest Gauld",
    avatar: "https://robohash.org/quisquampariaturest.png?size=50x50&set=set1",
    university: "Veer Kunwar Singh University",
    department: "Accounting",
  },
  {
    id: 112,
    fullName: "Arlan Waldock",
    avatar: "https://robohash.org/nammodiquia.png?size=50x50&set=set1",
    university: "Universidad Don Vasco",
    department: "Accounting",
  },
  {
    id: 113,
    fullName: "Blinni Ladon",
    avatar: "https://robohash.org/recusandaecumaut.png?size=50x50&set=set1",
    university: "Libera Università degli Studi di Scienze Umane e Tecnologiche",
    department: "Training",
  },
  {
    id: 114,
    fullName: "Morrie Flay",
    avatar: "https://robohash.org/solutaetmolestiae.png?size=50x50&set=set1",
    university: "Queen Mary and Westfield College, University of London",
    department: "Services",
  },
  {
    id: 115,
    fullName: "Sharona Whittenbury",
    avatar: "https://robohash.org/utimpeditvoluptate.png?size=50x50&set=set1",
    university: "Epoka University",
    department: "Business Development",
  },
  {
    id: 116,
    fullName: "Rossy Johnikin",
    avatar: "https://robohash.org/automnissit.png?size=50x50&set=set1",
    university: "Technical Institute of Dubnica in Dubnica nad Váhom",
    department: "Legal",
  },
  {
    id: 117,
    fullName: "Davida Minett",
    avatar:
      "https://robohash.org/inciduntquisvoluptatum.png?size=50x50&set=set1",
    university: "University of Tennessee Space Institute",
    department: "Support",
  },
  {
    id: 118,
    fullName: "Evey McArthur",
    avatar: "https://robohash.org/deseruntmaximead.png?size=50x50&set=set1",
    university: "Instituto Superior D. Afonso III - INUAF",
    department: "Product Management",
  },
  {
    id: 119,
    fullName: "Malory Bennet",
    avatar:
      "https://robohash.org/quirecusandaelaboriosam.png?size=50x50&set=set1",
    university: "Fachhochschule für Technik und Wirtschaft Berlin",
    department: "Services",
  },
  {
    id: 120,
    fullName: "Janey Revie",
    avatar: "https://robohash.org/nihilautperspiciatis.png?size=50x50&set=set1",
    university: "Universidad de Especialidades del Espíritu Santo",
    department: "Engineering",
  },
  {
    id: 121,
    fullName: "Boris Wallen",
    avatar: "https://robohash.org/remestut.png?size=50x50&set=set1",
    university: "Centro Regional Universitário de Espiríto Santo do Pinhal",
    department: "Research and Development",
  },
  {
    id: 122,
    fullName: "Gypsy Sharland",
    avatar:
      "https://robohash.org/commodideseruntrepudiandae.png?size=50x50&set=set1",
    university: "University of Phoenix",
    department: "Research and Development",
  },
  {
    id: 123,
    fullName: "Ludvig Matzeitis",
    avatar: "https://robohash.org/errordolornatus.png?size=50x50&set=set1",
    university: "Tottori University of Environmental Studies",
    department: "Human Resources",
  },
  {
    id: 124,
    fullName: "Gena Buard",
    avatar: "https://robohash.org/nondoloremfacilis.png?size=50x50&set=set1",
    university: "University of Mostar",
    department: "Marketing",
  },
  {
    id: 125,
    fullName: "Holt Stowers",
    avatar: "https://robohash.org/namvoluptatemdolor.png?size=50x50&set=set1",
    university: "Xinjiang University",
    department: "Human Resources",
  },
  {
    id: 126,
    fullName: "Amby Arnaldy",
    avatar: "https://robohash.org/eumducimuset.png?size=50x50&set=set1",
    university: "Alderson Broaddus College",
    department: "Human Resources",
  },
  {
    id: 127,
    fullName: "Britt Keunemann",
    avatar:
      "https://robohash.org/explicabodeseruntsunt.png?size=50x50&set=set1",
    university: "Royal Academy of Music, University of London",
    department: "Sales",
  },
  {
    id: 128,
    fullName: "Marleen Willmott",
    avatar: "https://robohash.org/quosenimmolestiae.png?size=50x50&set=set1",
    university: "University of Leicester",
    department: "Accounting",
  },
  {
    id: 129,
    fullName: "Antin Bann",
    avatar: "https://robohash.org/sedutaut.png?size=50x50&set=set1",
    university: "Humphreys College",
    department: "Accounting",
  },
  {
    id: 130,
    fullName: "Mara Brotherton",
    avatar: "https://robohash.org/autreiciendisnisi.png?size=50x50&set=set1",
    university: "Institut Teknologi Adhi Tama Surabaya",
    department: "Marketing",
  },
  {
    id: 131,
    fullName: "Emeline Challace",
    avatar: "https://robohash.org/quamnisinam.png?size=50x50&set=set1",
    university: "Western State University College of Law",
    department: "Research and Development",
  },
  {
    id: 132,
    fullName: "Lammond Fernandes",
    avatar: "https://robohash.org/quomolestiassit.png?size=50x50&set=set1",
    university: "International Institute for Population Sciences",
    department: "Product Management",
  },
  {
    id: 133,
    fullName: "Denna Iorizzi",
    avatar: "https://robohash.org/adeosexplicabo.png?size=50x50&set=set1",
    university: "University of LaVerne in Athens",
    department: "Training",
  },
  {
    id: 134,
    fullName: "Selia Kusick",
    avatar: "https://robohash.org/illumautemquam.png?size=50x50&set=set1",
    university: "Premier University",
    department: "Training",
  },
  {
    id: 135,
    fullName: "Judas Pendry",
    avatar: "https://robohash.org/velitsequivoluptatem.png?size=50x50&set=set1",
    university: "FAE Business School - Faculdade de Administração e Economia",
    department: "Marketing",
  },
  {
    id: 136,
    fullName: "Chaunce Hiland",
    avatar: "https://robohash.org/quidemvoluptateut.png?size=50x50&set=set1",
    university: "Ecole Supérieure de Commerce de Dijon",
    department: "Legal",
  },
  {
    id: 137,
    fullName: "Brian Maffin",
    avatar: "https://robohash.org/nesciuntidexplicabo.png?size=50x50&set=set1",
    university: "Presbyterian College",
    department: "Accounting",
  },
  {
    id: 138,
    fullName: "Lucho Prin",
    avatar:
      "https://robohash.org/dignissimoslaborebeatae.png?size=50x50&set=set1",
    university: "McGill University",
    department: "Marketing",
  },
  {
    id: 139,
    fullName: "Dolli Zorzi",
    avatar: "https://robohash.org/autremhic.png?size=50x50&set=set1",
    university: "Lund University",
    department: "Accounting",
  },
  {
    id: 140,
    fullName: "Barr Kalvin",
    avatar: "https://robohash.org/inmaximeest.png?size=50x50&set=set1",
    university: "University of Connecticut at Hartford",
    department: "Sales",
  },
  {
    id: 141,
    fullName: "Leighton Pinner",
    avatar:
      "https://robohash.org/laborumnihilvoluptatum.png?size=50x50&set=set1",
    university: "Western State University College of Law - Orange County",
    department: "Marketing",
  },
  {
    id: 142,
    fullName: "Udell Madle",
    avatar: "https://robohash.org/nonhiccumque.png?size=50x50&set=set1",
    university: "Instituto Politécnico de Coimbra",
    department: "Sales",
  },
  {
    id: 143,
    fullName: "Yvor Parks",
    avatar: "https://robohash.org/aperiamsedillum.png?size=50x50&set=set1",
    university: "Reykjavík University",
    department: "Product Management",
  },
  {
    id: 144,
    fullName: "Russell Winspurr",
    avatar: "https://robohash.org/rerumiustoet.png?size=50x50&set=set1",
    university: "Kyoto Bunkyo University",
    department: "Accounting",
  },
  {
    id: 145,
    fullName: "Coop Moran",
    avatar:
      "https://robohash.org/optiodolorrepudiandae.png?size=50x50&set=set1",
    university: "Kwassui Women's College",
    department: "Training",
  },
  {
    id: 146,
    fullName: "Dennison Conechie",
    avatar: "https://robohash.org/rerumeasaepe.png?size=50x50&set=set1",
    university: "Plymouth State College",
    department: "Research and Development",
  },
  {
    id: 147,
    fullName: "Sarene McCosker",
    avatar: "https://robohash.org/totaminciduntlabore.png?size=50x50&set=set1",
    university: "Buraydah College for Applied Medical Sciences",
    department: "Marketing",
  },
  {
    id: 148,
    fullName: "Esra Gallie",
    avatar: "https://robohash.org/sedmaximeprovident.png?size=50x50&set=set1",
    university: "Türkisch-Deutsche Universität",
    department: "Research and Development",
  },
  {
    id: 149,
    fullName: "Ellie Daal",
    avatar: "https://robohash.org/illolaudantiumest.png?size=50x50&set=set1",
    university: "Northern Institute of Technology Management (NIT)",
    department: "Human Resources",
  },
  {
    id: 150,
    fullName: "Ruy Roos",
    avatar: "https://robohash.org/quispraesentiumat.png?size=50x50&set=set1",
    university: "Rak Medical & Health Sciences University",
    department: "Sales",
  },
  {
    id: 151,
    fullName: "Darn Teulier",
    avatar: "https://robohash.org/autquiaconsequatur.png?size=50x50&set=set1",
    university:
      "Central America Health Sciences University (Belize Medical College)",
    department: "Sales",
  },
  {
    id: 152,
    fullName: "Augusta Corpes",
    avatar: "https://robohash.org/etoptionumquam.png?size=50x50&set=set1",
    university: "Federal University of Technology, Owerri",
    department: "Training",
  },
  {
    id: 153,
    fullName: "Jemima McClurg",
    avatar: "https://robohash.org/optioeaqueaut.png?size=50x50&set=set1",
    university: "Connecticut College",
    department: "Legal",
  },
  {
    id: 154,
    fullName: "Idalina Sparrow",
    avatar: "https://robohash.org/ipsumestexcepturi.png?size=50x50&set=set1",
    university: "Hakodate University",
    department: "Accounting",
  },
  {
    id: 155,
    fullName: "Mahala Beardsell",
    avatar: "https://robohash.org/possimusenimdolores.png?size=50x50&set=set1",
    university: "Baiko Women's College",
    department: "Accounting",
  },
  {
    id: 156,
    fullName: "Rollo Howland",
    avatar: "https://robohash.org/abquiporro.png?size=50x50&set=set1",
    university: "University of Toronto, Mississauga",
    department: "Human Resources",
  },
  {
    id: 157,
    fullName: "Lucita Kirkwood",
    avatar: "https://robohash.org/etaliasmollitia.png?size=50x50&set=set1",
    university: "Iqra University",
    department: "Training",
  },
  {
    id: 158,
    fullName: "Kevina Fosh",
    avatar:
      "https://robohash.org/quaeconsecteturadipisci.png?size=50x50&set=set1",
    university: "Khulna University",
    department: "Research and Development",
  },
  {
    id: 159,
    fullName: "Tymothy De Domenico",
    avatar: "https://robohash.org/doloresdignissimoset.png?size=50x50&set=set1",
    university: "University of Colorado at Colorado Springs",
    department: "Accounting",
  },
  {
    id: 160,
    fullName: "Karoly Doxsey",
    avatar: "https://robohash.org/natusquibusdamat.png?size=50x50&set=set1",
    university: "Dawat University",
    department: "Engineering",
  },
  {
    id: 161,
    fullName: "Forster Skyner",
    avatar: "https://robohash.org/sitminimanon.png?size=50x50&set=set1",
    university: "Shiraz University",
    department: "Product Management",
  },
  {
    id: 162,
    fullName: "Shelley Ferrarin",
    avatar:
      "https://robohash.org/consequaturdolorerepudiandae.png?size=50x50&set=set1",
    university: "Wartburg College",
    department: "Services",
  },
  {
    id: 163,
    fullName: "Maure Rosetti",
    avatar:
      "https://robohash.org/magnamipsumvoluptates.png?size=50x50&set=set1",
    university: "Jai Prakash University",
    department: "Marketing",
  },
  {
    id: 164,
    fullName: "Iain Waddoups",
    avatar: "https://robohash.org/autsitblanditiis.png?size=50x50&set=set1",
    university: "Greenwich University",
    department: "Marketing",
  },
  {
    id: 165,
    fullName: "Erena Mollene",
    avatar: "https://robohash.org/eligendiestalias.png?size=50x50&set=set1",
    university: "University of Brighton",
    department: "Support",
  },
  {
    id: 166,
    fullName: "Modesty Pepis",
    avatar: "https://robohash.org/voluptatemvelitat.png?size=50x50&set=set1",
    university: "National Medical University O.O. Bogomolets",
    department: "Support",
  },
  {
    id: 167,
    fullName: "Rufe Lawland",
    avatar: "https://robohash.org/quisquiamolestias.png?size=50x50&set=set1",
    university: "National American University, Denver",
    department: "Product Management",
  },
  {
    id: 168,
    fullName: "Freddie Decent",
    avatar: "https://robohash.org/doloremdolorequidem.png?size=50x50&set=set1",
    university: "Université de Bangui",
    department: "Business Development",
  },
  {
    id: 169,
    fullName: "Brittni Brandin",
    avatar: "https://robohash.org/similiquevoluptasaut.png?size=50x50&set=set1",
    university: "Deaconess College of Nursing",
    department: "Product Management",
  },
  {
    id: 170,
    fullName: "Alvera Bodham",
    avatar: "https://robohash.org/utipsaquia.png?size=50x50&set=set1",
    university: "Omsk State Agrarian University",
    department: "Business Development",
  },
  {
    id: 171,
    fullName: "Margret Poll",
    avatar:
      "https://robohash.org/autemprovidentdolorem.png?size=50x50&set=set1",
    university: "Mother Teresa Women's University",
    department: "Services",
  },
  {
    id: 172,
    fullName: "Hollyanne Burnel",
    avatar: "https://robohash.org/quaeestaut.png?size=50x50&set=set1",
    university: "Institute of Teachers Education, Ipoh",
    department: "Product Management",
  },
  {
    id: 173,
    fullName: "Agosto Claris",
    avatar:
      "https://robohash.org/temporibusquiadeserunt.png?size=50x50&set=set1",
    university: "Universidad del Zulia",
    department: "Human Resources",
  },
  {
    id: 174,
    fullName: "Ellsworth Sawkin",
    avatar:
      "https://robohash.org/exercitationemdoloremcorporis.png?size=50x50&set=set1",
    university: "Mazandaran University of Medical Science",
    department: "Human Resources",
  },
  {
    id: 175,
    fullName: "Lorna Ewells",
    avatar:
      "https://robohash.org/voluptatemquosaperiam.png?size=50x50&set=set1",
    university: "Hochschule für Gestaltung und Kunst Zürich",
    department: "Support",
  },
  {
    id: 176,
    fullName: "Tish Pragnell",
    avatar: "https://robohash.org/earumlaborumneque.png?size=50x50&set=set1",
    university: "Zonguldak Karaelmas University",
    department: "Business Development",
  },
  {
    id: 177,
    fullName: "Johnnie Ledson",
    avatar:
      "https://robohash.org/doloremdoloresreprehenderit.png?size=50x50&set=set1",
    university: "Kobe University",
    department: "Engineering",
  },
  {
    id: 178,
    fullName: "Jodi Giacobo",
    avatar:
      "https://robohash.org/voluptatemolestiaeaut.png?size=50x50&set=set1",
    university: "Mary Baldwin College",
    department: "Marketing",
  },
  {
    id: 179,
    fullName: "Stirling des Remedios",
    avatar:
      "https://robohash.org/doloribusculpavoluptates.png?size=50x50&set=set1",
    university: "University of King's College",
    department: "Business Development",
  },
  {
    id: 180,
    fullName: "Mona Steade",
    avatar: "https://robohash.org/nonipsaeos.png?size=50x50&set=set1",
    university: "Loughborough University",
    department: "Support",
  },
  {
    id: 181,
    fullName: "Andee Sighard",
    avatar:
      "https://robohash.org/mollitiaperspiciatiset.png?size=50x50&set=set1",
    university: "ifs University College",
    department: "Accounting",
  },
  {
    id: 182,
    fullName: "Letty Malshinger",
    avatar: "https://robohash.org/estquodsaepe.png?size=50x50&set=set1",
    university: "Universidad Mayor de San Simón",
    department: "Sales",
  },
  {
    id: 183,
    fullName: "Vonnie Kynton",
    avatar:
      "https://robohash.org/commodipariaturquaerat.png?size=50x50&set=set1",
    university: "National Chiao Tung University",
    department: "Legal",
  },
  {
    id: 184,
    fullName: "Kellyann Lathan",
    avatar: "https://robohash.org/quiadoloremaut.png?size=50x50&set=set1",
    university: "Yazd University",
    department: "Accounting",
  },
  {
    id: 185,
    fullName: "Harmonia Hindes",
    avatar: "https://robohash.org/aliasdoloresdolore.png?size=50x50&set=set1",
    university: "La Salle University",
    department: "Legal",
  },
  {
    id: 186,
    fullName: "Stanly Albrooke",
    avatar: "https://robohash.org/suscipitlaudantiumex.png?size=50x50&set=set1",
    university: "Universidad Nacional de Cajamarca",
    department: "Accounting",
  },
  {
    id: 187,
    fullName: "Thornie Bjorkan",
    avatar: "https://robohash.org/utidomnis.png?size=50x50&set=set1",
    university: "Alverno College",
    department: "Human Resources",
  },
  {
    id: 188,
    fullName: "Marie Lougheed",
    avatar: "https://robohash.org/debitisquimolestiae.png?size=50x50&set=set1",
    university: "Azusa Pacific University",
    department: "Marketing",
  },
  {
    id: 189,
    fullName: "Leroi Valentine",
    avatar: "https://robohash.org/velsaepeminus.png?size=50x50&set=set1",
    university: "Future University",
    department: "Legal",
  },
  {
    id: 190,
    fullName: "Melinda Ginnelly",
    avatar:
      "https://robohash.org/laudantiumharumplaceat.png?size=50x50&set=set1",
    university: "Universidad Rey Juan Carlos",
    department: "Business Development",
  },
  {
    id: 191,
    fullName: "Sukey Petric",
    avatar:
      "https://robohash.org/quianecessitatibusaut.png?size=50x50&set=set1",
    university: "University of North Carolina at Greensboro",
    department: "Business Development",
  },
  {
    id: 192,
    fullName: "Clive Lubeck",
    avatar: "https://robohash.org/inciduntautet.png?size=50x50&set=set1",
    university: "European School of Economics",
    department: "Training",
  },
  {
    id: 193,
    fullName: "Dimitry Harmond",
    avatar: "https://robohash.org/sintvelitdignissimos.png?size=50x50&set=set1",
    university: "Tennessee State University",
    department: "Support",
  },
  {
    id: 194,
    fullName: "Oralie Caramuscia",
    avatar: "https://robohash.org/dolorquiaillum.png?size=50x50&set=set1",
    university: "Bar-Ilan University",
    department: "Human Resources",
  },
  {
    id: 195,
    fullName: "Osbourn Youtead",
    avatar: "https://robohash.org/quiavoluptatemalias.png?size=50x50&set=set1",
    university: "University of Winnipeg",
    department: "Marketing",
  },
  {
    id: 196,
    fullName: "Kristina Girardoni",
    avatar: "https://robohash.org/atconsequunturrem.png?size=50x50&set=set1",
    university: "Bayan College for Science & Technology",
    department: "Business Development",
  },
  {
    id: 197,
    fullName: "Blythe Stolting",
    avatar:
      "https://robohash.org/asperioresdoloremreprehenderit.png?size=50x50&set=set1",
    university: "Tierärztliche Hochschule Hannover",
    department: "Training",
  },
  {
    id: 198,
    fullName: "Dorie Piggrem",
    avatar: "https://robohash.org/odiorepellatnon.png?size=50x50&set=set1",
    university: "Dire Dawa University",
    department: "Business Development",
  },
  {
    id: 199,
    fullName: "Bernelle Brearton",
    avatar: "https://robohash.org/repellendusquiaenim.png?size=50x50&set=set1",
    university: "University of St. Jerome's College",
    department: "Marketing",
  },
  {
    id: 200,
    fullName: "Hatti Crighten",
    avatar: "https://robohash.org/fugiatmagnamexpedita.png?size=50x50&set=set1",
    university: "Dhaka University of Engineering and Technology",
    department: "Marketing",
  },
];

data.forEach(({ avatar, department, fullName, university }) => {
  const cardList = document.querySelector(".cardList");
  cardList.insertAdjacentHTML(
    "beforeend",
    `
    <div class="card">
      <div class="left">
        <div class="imageBox">
          <img src="${avatar}" alt="">
        </div>
      </div>
      <div class="right">
        <div class="name">${fullName}</div>
        <div class="info">
          <div class="university">${university}</div>
          <div class="department">${department}</div>
        </div>
      </div>
    </div>
  `
  );
});
